apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{include "veganpro.fullname" . }}
spec:
  maxReplicas: {{ .Values.veganpro.maxReplicas }}
  minReplicas: {{ .Values.veganpro.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{include "veganpro.fullname" . }}
  targetCPUUtilizationPercentage: {{ .Values.veganpro.targetCPUUtilizationPercentage }}
