kind: Service
apiVersion: v1
metadata:
  name: {{include "veganpro.fullname" . }}-stable
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }} 
    targetPort: {{ .Values.service.targetPort }}
    name: {{ .Values.veganpro.nameOverride }}
  selector:
      {{- if .Values.canary.enable }}
      {{- include "veganpro.selectlabels.false" . | nindent 4 }}
      {{- end }}
      {{- if not .Values.canary.enable }}
      {{- include "veganpro.selectorLabels" . | nindent 4 }}
      {{- end }}
  type: {{ .Values.service.type }}
