{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: vegan-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}   
spec:
  rules:
  - host: {{ .Values.ingress.hosts }}
    http:
      paths:
      - path:
        backend:
          serviceName: {{ .Values.vegan.nameOverride}}
          servicePort: {{ .Values.vegan.serverPort }}
  tls:
  - hosts:
    - {{ .Values.ingress.hosts }}
    secretName: {{ .Values.ingress.secretName }}
      {{- else }}
        null
      {{- end }}
