apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{include "vegan.fullname" . }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods","services","endpoints","namespaces","configmaps"]
    verbs: ["get","list","watch","create","delete","update"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{include "vegan.fullname" . }}
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{include "vegan.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{include "vegan.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.vegan.nameOverride }}
  namespace: {{ .Values.namespace }}
