apiVersion: v1
kind: Service
metadata:
  name: {{include "vegan.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
      name: {{include "vegan.fullname" . }}
  selector:
    {{- include "vegan.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}

